#!/usr/bin/env node
// Bump the MarkGo for Windows version everywhere it is declared, commit, and
// tag a release. Pushing the `win-v*` tag triggers the GitHub Actions workflow,
// which builds the signed installers + latest.json and publishes a Release that
// the in-app auto-updater reads.
//
// Usage:
//   node scripts/release-win.mjs <x.y.z>           # bump, commit, tag (no push)
//   node scripts/release-win.mjs <x.y.z> --push    # also push commit + tag
//
// Run from the repo root (or anywhere — paths resolve relative to this file).

import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const version = process.argv[2];
const push = process.argv.includes("--push");

if (!version || !/^\d+\.\d+\.\d+$/.test(version)) {
  console.error("用法: node scripts/release-win.mjs <x.y.z> [--push]");
  process.exit(1);
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const win = resolve(root, "platforms/windows");
const SEMVER = String.raw`\d+\.\d+\.\d+`;

// [file, regex, label, fatal] — fatal:false means "warn but continue" (the file
// is regenerated by the build, e.g. Cargo.lock).
const targets = [
  ["package.json", new RegExp(`("version"\\s*:\\s*")${SEMVER}(")`), "package.json", true],
  ["src-tauri/tauri.conf.json", new RegExp(`("version"\\s*:\\s*")${SEMVER}(")`), "tauri.conf.json", true],
  ["src-tauri/Cargo.toml", new RegExp(`(\\nversion\\s*=\\s*")${SEMVER}(")`), "Cargo.toml", true],
  ["src-tauri/Cargo.lock", new RegExp(`(name = "markgo-win"\\nversion = ")${SEMVER}(")`), "Cargo.lock", false],
];

const changed = [];
for (const [file, regex, label, fatal] of targets) {
  const path = resolve(win, file);
  const before = readFileSync(path, "utf8");
  const after = before.replace(regex, `$1${version}$2`);
  if (before === after) {
    if (fatal) {
      console.error(`✗ 未能在 ${label} 中找到/替换版本号`);
      process.exit(1);
    }
    console.warn(`· 跳过 ${label}（未找到版本行，构建时会自动更新）`);
    continue;
  }
  writeFileSync(path, after);
  changed.push(`platforms/windows/${file}`);
  console.log(`✔ ${label} → ${version}`);
}

const tag = `win-v${version}`;
// Pass args as an array (no shell) so nothing is interpolated into a command
// string; `version` is already validated as strict semver above.
const git = (...args) => execFileSync("git", args, { cwd: root, stdio: "inherit" });

git("add", ...changed);
git("commit", "-m", `release(windows): v${version}`);
git("tag", tag);
console.log(`\n已提交并打标签 ${tag}。`);

if (push) {
  git("push", "origin", "HEAD", tag);
  console.log("已推送。GitHub Actions 将构建签名安装包并发布 Release，旧版本会自动更新上来。");
} else {
  console.log(`未推送。运行以下命令触发发布：\n  git push origin HEAD ${tag}`);
}
